#/*
#*********************************************************************************************************
#*                                                    MELIS
#*                                    the Easy Portable/Player Develop Kits
#*                                               makefile Module
#*
#*                                    (c) Copyright 2006-2010, kevin.z China
#*                                             All Rights Reserved
#*
#* File    : makefile
#* By      : kevin.z
#* Version : v1.0
#* Date    : 2010-9-7 11:24
#* Descript:
#* Update  : date                auther      ver     notes
#*********************************************************************************************************
#*/

all:
	make -f makelib

kernel:
	make -f makekrnl

kernel_uart:
	make -f makekrnl_uart


# 删除生成的中间文件
clean:
	make -f makelib clean

	@echo clean temp file!
