;///*
;//*********************************************************************************************************
;//*											        ePOS
;//*						           the Easy Portable/Player Operation System
;//*									           MEMS sub-system
;//*
;//*						        (c) Copyright 2006-2007, Steven.ZGJ China
;//*											All	Rights Reserved
;//*
;//* File   : elibs_i.inc
;//* Version: V1.0
;//* By     : steven.zgj
;//*********************************************************************************************************
;//*/
        if :LNOT::DEF:_ELIBS_I_INC_
	    GBLA          _ELIBS_I_INC_

        include cfgs.inc
        

 	
 	    endif     ;//  IF :LNOT::DEF:_ELIBS_I_INC_
	    end    
	
	