call cc doassert
call cc docat
call cc docd
call cc docopy
call cc docreate
call cc dodel
call cc dodir
call cc dofs
call cc dohelp
call cc dohistory
call cc doinsmod
call cc dokeysim
call cc dopoweroff
call cc domount
call cc domkdir
call cc doreset
call cc dormdir
call cc dosetpath
call cc dosendkey
call cc dostartx
call cc dosysinfo
call cc dorun
call cc dowait
call cc doxcopy
call cc doformatcheck
call cc doformat
call cc doshowdsize
call cc doshowfsize
call cc doconfigfs
call pk doscript
call cc docpustat
call cc dode
call cc domeminfo
call cc doquit
call pk doupdate
call pk doregrd
