call cc doscript
call cc Esh_script_area
call cc Esh_script_domisc
call cc Esh_script_eval
call cc Esh_script_executer
call cc Esh_script_lexer
call cc Esh_script_onecommand
call cc Esh_script_parser
call cc Esh_script_var
