call pl lib
call pl foundation
call cl robin_i
call pl palette
call pl disp_output
call pl ab
call pl channel
call pl eq
call pl ff_rr_speed
call pl fsm_ctrl
call pl lyric
call pl media_info
call pl npl
call pl play_mode
call pl play_speed
call pl spectrum
call pl star
call pl subtitle
call pl track
call pl video_layer
call pl video_win
call pl vision_effect
call pl volume
call pl zoom
call cl robin
